### ISSUE TITLE
my.openhab addon

### ISSUE THREAD

**Issue by Shmixx** [tdeckers/docker-openhab#14]
It seems I was having trouble getting the my.openhab add-on to correctly map in the configuration add ons.cfg file. Entering the container I can see that there are 2 versions with the same name (1.7.0 / 1.7.1) so I renamed the 1.7.0 file to a different name. After doing so the mapping worked fine. Likely want to remove that extra add-on from the addons-available directory.

**Comment by tdeckers** [comment]
Fixed by joltcoke

**Comment by Shmixx** [comment]
Just wanted to let you know that it doesn't seem this was actually fixed. I just setup a new docker host and made the appropriate changes to get it up and running but didn't touch the my.openhab jar files this time. The fix from Joltcoke addressed an issue with the demo config if I understand the history correct. There was a Branch Improvements section that had some changes to the my.openhab piece, and it looks like that piece is what's causing the 2 versions of org.openhab.io.myopenhab binding to be existing. 
I'm sorry I can't help trying to illustrate via Git pull request and actual code fixes, I'm not quite that efficient and knowledgeable. I'm hoping to get a handle on it soon though and make 2 other suggested changes to address enabling SSL during creation.
