### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by hjnijlunsing** [tdeckers/docker-openhab#23]
When running the example there seems to be a "/" where it should be a space in:
`docker run -d -p 8080:8080 -v /tmp/configuration:/etc/openhab/tdeckers/openhab`
Should be:
`docker run -d -p 8080:8080 -v /tmp/configuration:/etc/openhab tdeckers/openhab`

**Comment by tdeckers** [comment]
Thank you! Fixed in next push.
