### ISSUE TITLE
Any chance you can add habmin?

### ISSUE THREAD

**Issue by dprus** [tdeckers/docker-openhab#4]
It would help use OpenHAB newbies out a lot :)

**Comment by dprus** [comment]
OK, I was able to add habmin myself by running docker-openhab as follows:
```
docker run -d -p 192.168.0.2:58080:8080 --name=openhab -v /volume1/docker/openhab/webapps/habmin:/opt/openhab/webapps/habmin -v /volume1/docker/openhab/config:/etc/openhab -v /volume1/docker/openhab/addons-available/habmin:/opt/openhab/addons-available/habmin tdeckers/openhab
```
I'm not entirely sure if this is a supported method but it does work. I also add to add the following to addons.cfg:
```
habmin/org.openhab.binding.zwave-1.7.0
habmin/org.openhab.io.habmin-1.7.0
```
Hopefully this helps out anyone else wishing to do the same.

**Comment by tdeckers** [comment]
Apologies for the delay, but thanks for the feedback.  I'll add a note in the docs to highlight your solution.
