### ISSUE TITLE
Telnet to 5555 to access osgi isn't working

### ISSUE THREAD

**Issue by dprus** [tdeckers/docker-openhab#7]
I've got -p "127.0.0.1:5555:5555" in my docker run command. After that I run: "telnet localhost 5555" from my host machine but I'm not able to connect to the osgi console interface.

Should you be specifying the port (5555) after the -console command when you run the OpenHAB jar?

**Comment by dprus** [comment]
I think I just confirmed this by installing and running lsof on my running instance of docker-openhab:
```
richard@server:~$ docker exec openhab lsof -i TCP
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
superviso   1 root    4u  IPv4  39788      0t0  TCP *:9001 (LISTEN)
java       30 root  116u  IPv6  40534      0t0  TCP *:http-alt (LISTEN)
java       30 root  125u  IPv6  39801      0t0  TCP be541bbedbcb:http-alt->main-pc.local:59278 (ESTABLISHED)
java       30 root  129u  IPv6  39806      0t0  TCP *:8443 (LISTEN)
```

**Comment by tdeckers** [comment]
Thanks for the pull request.  I finally got around to merge it.
